# Generated by Django 2.0 on 2020-05-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddEnvLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnvPar', models.CharField(max_length=8, null=True)),
                ('ServerUser', models.CharField(max_length=12)),
                ('ServerPass', models.CharField(max_length=32)),
                ('RepoAddress', models.CharField(max_length=64)),
                ('RepoUser', models.CharField(max_length=64)),
                ('RepoPass', models.CharField(max_length=64)),
                ('JenkinsDir', models.CharField(max_length=128)),
                ('RootDir', models.CharField(max_length=64)),
                ('BackupDir', models.CharField(max_length=64)),
                ('EurekaAddress', models.CharField(max_length=64)),
                ('Hosts', models.CharField(max_length=102400)),
                ('CreateTime', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddServerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.CharField(max_length=32)),
                ('Node', models.CharField(max_length=128)),
                ('Port', models.CharField(max_length=6)),
                ('MemSize', models.CharField(max_length=6)),
                ('CheckOpsApi', models.CharField(max_length=128)),
                ('ServerType', models.CharField(max_length=6)),
                ('ReSet', models.CharField(max_length=4)),
                ('CreateTime', models.CharField(max_length=20)),
                ('Remarks', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnvInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnvPar', models.CharField(max_length=8, null=True)),
                ('ServerUser', models.CharField(max_length=12)),
                ('ServerPass', models.CharField(max_length=32)),
                ('RepoAddress', models.CharField(max_length=64)),
                ('RepoUser', models.CharField(max_length=64)),
                ('RepoPass', models.CharField(max_length=64)),
                ('JenkinsDir', models.CharField(max_length=128)),
                ('RootDir', models.CharField(max_length=64)),
                ('BackupDir', models.CharField(max_length=64)),
                ('EurekaAddress', models.CharField(max_length=64)),
                ('Hosts', models.CharField(max_length=102400)),
                ('ModifyTime', models.CharField(max_length=20, null=True)),
                ('CreateTime', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModifyEnvLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnvPar', models.CharField(max_length=8, null=True)),
                ('ServerUser', models.CharField(max_length=12)),
                ('ServerPass', models.CharField(max_length=32)),
                ('RepoAddress', models.CharField(max_length=64)),
                ('RepoUser', models.CharField(max_length=64)),
                ('RepoPass', models.CharField(max_length=64)),
                ('JenkinsDir', models.CharField(max_length=128)),
                ('RootDir', models.CharField(max_length=64)),
                ('BackupDir', models.CharField(max_length=64)),
                ('EurekaAddress', models.CharField(max_length=64)),
                ('Hosts', models.CharField(max_length=102400, null=True)),
                ('ModifyTime', models.CharField(max_length=20, null=True)),
                ('Remarks', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModifyServerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.CharField(max_length=32)),
                ('CheckOpsApi', models.CharField(max_length=128)),
                ('ServerType', models.CharField(max_length=6)),
                ('ReSet', models.CharField(max_length=4)),
                ('ModifyTime', models.CharField(max_length=20)),
                ('Remarks', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.CharField(max_length=32)),
                ('EnvPar', models.CharField(max_length=8, null=True)),
                ('Node', models.CharField(max_length=128)),
                ('Port', models.CharField(max_length=6)),
                ('MemSize', models.CharField(max_length=6)),
                ('ModifyTime', models.CharField(max_length=20, null=True)),
                ('CreateTime', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.CharField(max_length=32)),
                ('Node', models.CharField(max_length=128)),
                ('Port', models.CharField(max_length=6)),
                ('MemSize', models.CharField(max_length=6)),
                ('CheckOpsApi', models.CharField(max_length=128)),
                ('ServerType', models.CharField(max_length=6)),
                ('ReSet', models.CharField(max_length=4)),
                ('ModifyTime', models.CharField(max_length=20, null=True)),
                ('CreateTime', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
