# Generated by Django 2.0 on 2020-05-15 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverlist',
            name='MemSize',
        ),
        migrations.RemoveField(
            model_name='serverlist',
            name='Node',
        ),
        migrations.RemoveField(
            model_name='serverlist',
            name='Port',
        ),
    ]
