# Generated by Django 2.0 on 2020-05-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0002_auto_20200515_1415'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServerList',
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='CheckOpsApi',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='ReSet',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='ServerType',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
