# Generated by Django 2.0 on 2020-05-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0003_auto_20200515_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifyserverlog',
            name='MemSize',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='modifyserverlog',
            name='Node',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='modifyserverlog',
            name='Port',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
