# Generated by Django 2.0 on 2020-05-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0004_auto_20200515_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifyserverlog',
            name='ModifyUser',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
