# Generated by Django 2.0 on 2020-05-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0005_modifyserverlog_modifyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifyenvlog',
            name='ModifyUser',
            field=models.CharField(default='zxx', max_length=32),
            preserve_default=False,
        ),
    ]
