# Generated by Django 2.0 on 2020-05-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0006_modifyenvlog_modifyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinfo',
            name='Del',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
