# Generated by Django 2.0 on 2020-05-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0007_serverinfo_del'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifyserverlog',
            name='EnvPar',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
