# Generated by Django 2.0 on 2020-05-25 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0009_projectinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServerInfo',
        ),
    ]
