# Generated by Django 2.0 on 2020-06-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0010_delete_serverinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='LoadTengine',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='ReTengine',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
