# Generated by Django 2.0 on 2020-06-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0011_auto_20200606_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectinfo',
            old_name='LoadTengine',
            new_name='TenProxy',
        ),
    ]
