# Generated by Django 2.0 on 2020-06-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0012_auto_20200606_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='OldNode',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='OldNodeRm',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
