# Generated by Django 2.0 on 2020-06-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0013_auto_20200606_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='envinfo',
            name='TenDir',
            field=models.CharField(default='/usr/local/tengine/conf/conf.d/upstream', max_length=64),
            preserve_default=False,
        ),
    ]
