# Generated by Django 2.0 on 2020-06-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0015_projectinfo_oldport'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='ProjectStatus',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
