# Generated by Django 2.0 on 2020-06-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0016_projectinfo_projectstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='ProjectStatus',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
