# Generated by Django 2.0 on 2020-06-28 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0018_envconnlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnvConnList',
            new_name='EnvConnInfo',
        ),
    ]
