# Generated by Django 2.0 on 2020-06-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0020_addenvconnlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifyEnvConnLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnvPar', models.CharField(default=0, max_length=8, null=True)),
                ('KafkaInt', models.CharField(default=0, max_length=256, null=True)),
                ('KafkaExt', models.CharField(default=0, max_length=256, null=True)),
                ('HbaseInt', models.CharField(default=0, max_length=256, null=True)),
                ('HbaseExt', models.CharField(default=0, max_length=256, null=True)),
                ('HbaseUser', models.CharField(default=0, max_length=32, null=True)),
                ('HbasePass', models.CharField(default=0, max_length=128, null=True)),
                ('MysqlInt', models.CharField(default=0, max_length=256, null=True)),
                ('MysqlExt', models.CharField(default=0, max_length=256, null=True)),
                ('MysqlUser', models.CharField(default=0, max_length=32, null=True)),
                ('MysqlPass', models.CharField(default=0, max_length=128, null=True)),
                ('RedisInt', models.CharField(default=0, max_length=256, null=True)),
                ('RedisExt', models.CharField(default=0, max_length=256, null=True)),
                ('RedisPass', models.CharField(default=0, max_length=128, null=True)),
                ('ModifyTime', models.CharField(default=0, max_length=20, null=True)),
            ],
        ),
    ]
