# Generated by Django 2.0 on 2020-06-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0021_modifyenvconnlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='addenvconnlog',
            name='ModifyTime',
            field=models.CharField(default=0, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='modifyenvconnlog',
            name='ModifyUser',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
