# Generated by Django 2.0 on 2020-06-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0022_auto_20200628_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='envconninfo',
            name='ModifyTime',
            field=models.CharField(default=0, max_length=20, null=True),
        ),
    ]
