# Generated by Django 2.0 on 2020-07-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0024_auto_20200628_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='addserverlog',
            name='Belong',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='modifyserverlog',
            name='Belong',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='Belong',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
