# Generated by Django 2.0 on 2020-07-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0025_auto_20200701_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='ReleaseTime',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
