# Generated by Django 2.0 on 2020-07-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0026_projectinfo_releasetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crontab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CrontabName', models.CharField(max_length=64)),
                ('ExecPloy', models.CharField(default=0, max_length=32, null=True)),
                ('CreateTime', models.CharField(default=0, max_length=20, null=True)),
                ('ModifyTime', models.CharField(max_length=20)),
            ],
        ),
    ]
