# Generated by Django 2.0 on 2020-07-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0027_crontab'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='CheckApiTime',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
