# Generated by Django 2.0 on 2020-07-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0029_auto_20200703_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronexecreco',
            name='From',
            field=models.CharField(default='CrsDevOps', max_length=32),
            preserve_default=False,
        ),
    ]
