# Generated by Django 2.0 on 2020-07-05 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0030_cronexecreco_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronexecreco',
            old_name='From',
            new_name='Who',
        ),
    ]
