# Generated by Django 2.0 on 2020-07-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0031_auto_20200705_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='ProjectStatus',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
