# Generated by Django 2.0 on 2020-07-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0032_auto_20200705_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='envinfo',
            name='JavaCmd',
            field=models.CharField(default='', max_length=102400),
            preserve_default=False,
        ),
    ]
