# Generated by Django 2.0 on 2020-07-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0033_envinfo_javacmd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envinfo',
            name='JavaCmd',
            field=models.CharField(max_length=1024),
        ),
    ]
