# Generated by Django 2.0 on 2020-07-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0034_auto_20200710_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envinfo',
            name='Hosts',
            field=models.CharField(max_length=10240),
        ),
        migrations.AlterField(
            model_name='envinfo',
            name='JavaCmd',
            field=models.CharField(max_length=10240),
        ),
    ]
