# Generated by Django 2.0 on 2020-07-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0036_auto_20200710_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envinfo',
            name='JavaCmd',
            field=models.TextField(),
        ),
    ]
