# Generated by Django 2.0 on 2020-07-10 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0037_auto_20200710_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envinfo',
            name='JavaCmd',
        ),
    ]
