# Generated by Django 2.0 on 2020-07-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ops', '0038_remove_envinfo_javacmd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addenvlog',
            name='Hosts',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='envinfo',
            name='Hosts',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='modifyenvlog',
            name='Hosts',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
