# Generated by Django 2.2.7 on 2019-11-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20191113_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invita',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
