# Generated by Django 2.2.7 on 2019-11-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20191113_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invita',
            name='invitacode',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='invita',
            name='invitaname',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
