# Generated by Django 2.2.7 on 2019-11-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20191113_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=6, unique=True)),
                ('recode', models.CharField(max_length=6, null=True)),
                ('rename', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='invita',
            name='invitavercode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
