# Generated by Django 2.0 on 2020-05-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('invitacode', models.CharField(max_length=6, unique=True)),
                ('invitavercode', models.CharField(max_length=6, null=True)),
                ('invitaname', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=6, unique=True)),
                ('recode', models.CharField(max_length=6, null=True)),
            ],
        ),
    ]
