# Generated by Django 2.0 on 2020-05-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='c_time',
        ),
        migrations.AddField(
            model_name='user',
            name='CreateTime',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
