# Generated by Django 2.0 on 2020-05-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200518_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
