# Generated by Django 2.2.7 on 2019-11-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20191112_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invicode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
