# Generated by Django 2.2.7 on 2019-11-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20191113_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invita',
            name='invitaname',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
