# Generated by Django 2.2.7 on 2019-11-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20191113_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='c_time',
            field=models.DateField(),
        ),
    ]
