# Generated by Django 2.2.7 on 2019-11-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20191113_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vercode',
            name='rename',
        ),
    ]
