# Generated by Django 2.0 on 2020-07-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='Belong',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
